"""Database migration to postgresql

Revision ID: 31074e5ada6e
Revises: 7497b55d4fa4
Create Date: 2024-04-11 01:20:38.427238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31074e5ada6e"
down_revision: Union[str, None] = "7497b55d4fa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
